In [2]:
import time

In [3]:
a = list(range(1000000))
b = list(range(1000000))

start_p = time.perf_counter()
c = [x + y for x, y in zip(a, b)]
end_p = time.perf_counter()
total_p = end_p - start_p
print("Python:", total_p)

Python: 0.04614700000092853


In [5]:
import numpy as np

In [ ]:
a_np = np.array(a)
b_np = np.array(b)

start_n = time.perf_counter()
c_np = a_np + b_np
end_n = time.perf_counter()
total_n = end_n - start_n
print("NumPy:", total_n)

NumPy: 0.0018817000000126427


In [7]:
print(f"Numpy is faster than python by : {total_p/total_n:.2f}")

Numpy is faster than python by : 24.52


# Numpy

Python lists are : 
 - Flexible but slowfor numerical operations
 - Not designed for matrix math or
 - Does not support vectorised operation
 - Are memory inefficient for large numerical data

Why use numpy?
- Fast than pure python for numerical computation
- Vectorized operation (no explicit loops)
- Broadcasting (operate on arrays of different shape)
- Memory efficient
- Comes with powerful linear algebra, random tools etc

Use of numpy :
- Scientific python

In [ ]:
# !pip install numpy

In [8]:
import numpy as np

# creating arrays in numpy

### 1. np.array()

In [11]:
arr_1 = np.array([1,2,3])

print(arr_1)
print(type(arr_1))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
arr_1

array([1, 2, 3])

In [16]:
type(arr_1[0])

numpy.int64

In [ ]:
arr_2 = np.array([[1,2,3], [4,5,6]])

print(arr_2)

[[1 2 3]
 [4 5 6]]


In [22]:
arr_2[0]

array([1, 2, 3])

In [23]:
arr_2[0][2]

np.int64(3)

In [24]:
arr_2[1][2]

np.int64(6)

In [13]:
arr_3 = np.array([1,2,3, "hello"])

print(arr_3)
print(type(arr_3))

['1' '2' '3' 'hello']
<class 'numpy.ndarray'>


In [17]:
print(type(arr_3[1]))

<class 'numpy.str_'>


In [14]:
arr_4 = np.array([1,2,3], dtype=np.int8)
print(type(arr_4))

<class 'numpy.ndarray'>


In [15]:
type(arr_4[0])

numpy.int8

In [18]:
arr_5 = np.array([1,2,3, "hello"], dtype=np.float16)

ValueError: could not convert string to float: 'hello'

In [19]:
arr_6 = np.array([1,2,3, "10"], dtype=np.float16)

In [20]:
arr_6

array([ 1.,  2.,  3., 10.], dtype=float16)

In [ ]:
# arrays can have elements with only one data type

### 2. np.arange(start, stop, step)

In [26]:
list(range(1, 11, 2))

[1, 3, 5, 7, 9]

In [33]:
b = np.arange(1, 11, 2)

In [34]:
b

array([1, 3, 5, 7, 9])

### 3. np.linspace(start, stop, num=x)
stop - inclusive

In [36]:
np_linspace_1 = np.linspace(1,100,4)
print(np_linspace_1)
print(type(np_linspace_1))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [39]:
np_linspace_2 = np.linspace(1,10,10)
print(np_linspace_2)
print(type(np_linspace_2))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


In [44]:
for num in np.linspace(1,10,10):
    # print(type(num))
    print(num)
    # print(type(int(num)))
    # print("=================")

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [45]:
for num in np.linspace(1,10,10, dtype=np.int8):
    print(num)

1
2
3
4
5
6
7
8
9
10


### 4. np.zeros(shape)

shape -> shape of matrix

In [46]:
npz_1 = np.zeros(5)

In [47]:
npz_1

array([0., 0., 0., 0., 0.])

In [49]:
npz_2 = np.zeros((5,5), dtype=np.int8)
print(npz_2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [51]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [52]:
npz_3.ndim

3