## **NUMPY 3**

In [ ]:
## what is difference between array and matrix ?
## VEctorization ?

In [1]:
##

In [3]:
import numpy as np 

In [ ]:
## Matrix Mulitplication #####

In [ ]:
### AGGREGATION ########
## mean 
## sum 
## median 
## standard Deviation  ==> ? 
## CUMULATIVE SUM 
## np.dot ===> @
## argmin, argmax

In [ ]:
np.bincount()

In [7]:
arr = np.arange(8).reshape(2,2,2)
arr

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
for x in np.nditer(arr):
    print(x)

0
1
2
3
4
5
6
7


In [10]:
a  = np.array([1,2,3])
b = a.view()
a == b 

print(id(a))
print(id(b))

2485230773968
2485357477008


In [11]:
b[0] = 550

In [12]:
print(a)
print(b)

[550   2   3]
[550   2   3]


In [ ]:
# VSTACK 

In [ ]:
################# NUMPY ###########################
############ Char & strings #######################
